 version: "3.3"

 services:
   api-students:
     image: rodari78/api-students
     ports:
       - 8000:8000
   websimple:
     image: rodari78/websimple
     ports:
       - 8080:80
   webplantilla:
     image: rodari78/webplantilla
     ports:
       - 8081:80